#ifndef TX_USER_H
#define TX_USER_H

#define SYSTEM_CLOCKS_FREQUENCY     800000000
#define SYSTEM_TICKS_FREQUENCY      1000

#define TX_MAX_PRIORITIES           32
#define TX_TIMER_TICKS_PER_SECOND   SYSTEM_TICKS_FREQUENCY

#endif
